### ISSUE TITLE
Please provide a description

### ISSUE THREAD

**Issue by pcav** [sshuair/geohey-toolbox#2]
Adding it to metadata.
Thanks.

**Comment by sshuair** [comment]
Fixed, please check it.

**Comment by pcav** [comment]
Good, thanks.

**Comment by sshuair** [comment]
@pcav could you approve version 0.4?
![image](https://user-images.githubusercontent.com/5787131/48405414-2e5b7f80-e76d-11e8-9af0-ba8f3906daf2.png)

**Comment by pcav** [comment]
Done.

Il 13 novembre 2018 10:55:37 CET, sshuair <notifications@github.com> ha scritto:
>@pcav could you approve version 0.4?
>![image](https://user-images.githubusercontent.com/5787131/48405414-2e5b7f80-e76d-11e8-9af0-ba8f3906daf2.png)
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sshuair/geohey-toolbox/issues/2#issuecomment-438205364

-- 
Sorry for being short
