### ISSUE TITLE
model file naming error

### ISSUE THREAD

**Issue by liwind** [sshuair/geohey-toolbox#3]
### load geohey-toolbox-qgis3 error：
can‘t load plugin “geoheytoolbox”, error in calling method classFactory()
**ModuleNotFoundError**: No module named 'geoheytoolbox.geohey_toolbox_provider' 

###  the reason：
in model file geohey_toolbox.py import geohey_toolbox_provider,
but the model **geohey_toolbox_provider** is named as **geoHey_toolbox_provider.py** in original package,
that is the lower 'h' is the wrong way to the higher 'H' in **geohey**.

### the suggestion:
file name "geo**H**ey_toolbox_provider.py" is amended to "geo**h**ey_toolbox_provider.py"

**Comment by sshuair** [comment]
Fixed, try it again
