### ISSUE TITLE
why use ’a = 6378245.0‘？

### ISSUE THREAD

**Issue by 375000384** [sshuair/geohey-toolbox#6]
# define ellipsoid
a = 6378245.0
f = 1 / 298.3

why use 'a = 6378245.0',  rather than ‘a=6378137’ ？
'a = 6378245.0‘ is Krassovsky ellipsoid ,it is not a WGS84 ellipsoid

**Comment by 375000384** [comment]
'a = 6378245.0‘ is Krassovsky ellipsoid ,it is not a WGS84 ellipsoid

**Comment by warrenwyf** [comment]
That's how the offset algorithm is defined.

**Comment by yardern** [comment]
Would you be kind to let me know how to use this plugin?
I installed it in QGIS 3.32.3-Lima, but I could find it in "Plugins Toolbar".

Thanks.

> That's how the offset algorithm is defined.

**Comment by jlazygreen** [comment]
> Would you be kind to let me know how to use this plugin? I installed it in QGIS 3.32.3-Lima, but I could find it in "Plugins Toolbar".
> 
> Thanks.
> 
> > That's how the offset algorithm is defined.

When you installed the plugin, u can find it in the Processing Toolbox.

**Comment by yardern** [comment]
> > Would you be kind to let me know how to use this plugin? I installed it in QGIS 3.32.3-Lima, but I could find it in "Plugins Toolbar".
> > Thanks.
> > > That's how the offset algorithm is defined.
> 
> When you installed the plugin, u can find it in the Processing Toolbox.

Thanks. My QGIS had "Processing Toolbox" un-checked in the Plugins, so it took me a while to figure out.
