### ISSUE TITLE
wrapped C/C++ object of type WGS2GCJ has been deleted

### ISSUE THREAD

**Issue by hellorayza** [sshuair/geohey-toolbox#7]
It happened when I use coordinate transforms
```console info:
File "C:\Users/admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geohey_toolbox\geohey_toolbox_provider.py", line 66, in loadAlgorithms
              self.addAlgorithm( alg )
             RuntimeError: wrapped C/C++ object of type WGS2GCJ has been deleted
```

Environment:
```
QGIS version	3.26.1-Buenos Aires	QGIS code revision	b609df9ed4d
Qt version	5.15.3		
Python version	3.9.5		
GDAL/OGR version	3.5.1		
PROJ version	9.0.1		
EPSG Registry database version	v10.064 (2022-05-19)		
GEOS version	3.10.3-CAPI-1.16.1		
SQLite version	3.38.1		
PDAL version	2.3.0		
PostgreSQL client version	unknown		
SpatiaLite version	5.0.1		
QWT version	6.1.6		
QScintilla2 version	2.13.1		
OS version	Windows 10 Version 2009		
			
Active Python plugins			
geohey_toolbox	0.4		
db_manager	0.1.20		
grassprovider	2.12.99		
MetaSearch	0.3.6		
processing	2.12.99		
sagaprovider	2.12.99		

```

**Comment by yardern** [comment]
I saw the same message.

**Comment by warrenwyf** [comment]
> I saw the same message.

Is this issue relevant to the data? Would it be possible to share the data that went wrong?

**Comment by jlazygreen** [comment]
I tested the tools with open data on my device, and everything worked fine.
(point: https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_populated_places.zip,
 line: https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip,
polygon: https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_countries.zip).

Have you tried reinstalling your QGIS?

My Env:

```
QGIS version: 3.28.11-Firenze
QGIS code revision: d1af706d752
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.3.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.1.1, September 1st, 2021
PDAL version: 2.3.0 (git-version: Release)
```

**Comment by jlazygreen** [comment]
I got the same message when I installed the QGIS 3.32. Then I reinstalled the plugin, the error message disappeared.

**Comment by yardern** [comment]
> I got the same message when I installed the QGIS 3.32. Then I reinstalled the plugin, the error message disappeared.

The plugin was updated on 2023-10-25, it might have been fixed already.

**Comment by liuxspro** [comment]
This is a problem with the plugin created by Plugin Builder. see https://github.com/jdugge/BufferByPercentage/pull/14
Plugin builder has fixed this issue : https://github.com/g-sherman/Qgis-Plugin-Builder/issues/97
