### ISSUE TITLE
GeoHey Toolbox 转换后数据为空

### ISSUE THREAD

**Issue by LiHanGod** [sshuair/geohey-toolbox#9]
## GeoHey Toolbox 

- version
 
  Installed version	0.4.3

## QGIS 

- version

3.34.9-Prizren

![日志](https://github.com/user-attachments/assets/c3601467-546b-4316-8534-805947dce782)

![image](https://github.com/user-attachments/assets/6cd58301-f4f0-4467-b28c-fd5e0827b097)

这个是转换有什么问题吗

**Comment by jlazygreen** [comment]
你使用的数据是3D数据类型LinestringZ, 转成Linestring类型再用工具
